# Generated by Django 4.2.11 on 2024-05-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_light', '0002_alter_uploadimage_id'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='uploadimage',
        #     name='choice_field',
        #     field=models.CharField(choices=[('Accident', 'Accident'), ('Congestion', 'Congestion')], default='Accident', max_length=20),
        # ),
    ]
