# Generated by Django 4.2.11 on 2024-05-12 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_light', '0003_uploadimage_choice_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intersection',
            fields=[
                ('IntersectionID', models.AutoField(primary_key=True, serialize=False)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('NoOfTLs', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('Area', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OperationalStatus',
            fields=[
                ('StatusID', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficLight',
            fields=[
                ('TLID', models.AutoField(primary_key=True, serialize=False)),
                ('IntersectionID', models.IntegerField()),
                ('Number', models.IntegerField()),
                ('TrafficLightLatitude', models.FloatField()),
                ('TrafficLightLongitude', models.FloatField()),
                ('Status', models.CharField(max_length=20)),
                ('OperationalStatus', models.IntegerField()),
                ('GreenTime', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('IncidentID', models.AutoField(primary_key=True, serialize=False)),
                ('Image', models.ImageField(upload_to='images/')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Time', models.DateTimeField(auto_now=True)),
                ('IsAccident', models.BooleanField(default=False)),
                ('IsCongestion', models.BooleanField(default=False)),
                ('IntersectionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic_light.intersection')),
            ],
        ),
    ]
