# Generated by Django 4.2.11 on 2024-05-13 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_light', '0005_alter_incident_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='Image',
            field=models.ImageField(null=True, upload_to='incident_images'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='IntersectionID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='traffic_light.intersection'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='IsAccident',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='IsCongestion',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='Time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
