# Generated by Django 4.2.11 on 2024-05-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_light', '0008_alter_operationalstatus_status'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='operationalstatus',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, default=5, primary_key=True, serialize=False, verbose_name='ID'),
        #     preserve_default=False,
        # ),
        # migrations.AlterField(
        #     model_name='operationalstatus',
        #     name='StatusID',
        #     field=models.IntegerField(default=5),
        # ),
    ]
