# Generated by Django 4.2.11 on 2024-05-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_light', '0009_operationalstatus_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TF',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('isIncident', models.BooleanField()),
            ],
        ),
    ]
