# Generated by Django 4.2.11 on 2024-05-14 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_light', '0010_tf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'managed': False},
        ),
    ]
