# Generated by Django 4.2.11 on 2024-05-14 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_light', '0011_alter_incident_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='incident',
            table='Incident',
        ),
    ]
