# Generated by Django 4.2.11 on 2024-05-14 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_light', '0012_alter_incident_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OperationalStatus',
        ),
        migrations.DeleteModel(
            name='TF',
        ),
        migrations.DeleteModel(
            name='TrafficLight',
        ),
    ]
