# Generated by Django 4.2.11 on 2024-05-14 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_light', '0013_delete_operationalstatus_delete_tf_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Intersection',
        ),
    ]
