# Generated by Django 4.2.11 on 2024-05-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_light', '0014_delete_intersection'),
    ]

    operations = [
        migrations.CreateModel(
            name='operationalstatus',
            fields=[
                ('StatusID', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.CharField(max_length=20)),
            ],
        ),
    ]
