# Generated by Django 4.2.11 on 2024-05-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_light', '0015_operationalstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationalstatus',
            name='Status',
            field=models.CharField(default='Blue', max_length=20),
        ),
    ]
