# Generated by Django 4.2.11 on 2024-05-14 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_light', '0016_alter_operationalstatus_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationalstatus',
            options={'managed': False},
        ),
    ]
