# Generated by Django 4.2.11 on 2024-05-14 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_light', '0017_alter_operationalstatus_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='operationalstatus',
        ),
    ]
