# Generated by Django 4.2.11 on 2024-05-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_light', '0018_delete_operationalstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_field', models.CharField(choices=[('Accident', 'Accident'), ('Congestion', 'Congestion')], default='Accident', max_length=20)),
                ('image', models.ImageField(upload_to='images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        # migrations.DeleteModel(
        #     name='UploadImage',
        # ),
    ]
