# Generated by Django 4.2.11 on 2024-05-17 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_light', '0021_delete_uploadimage'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='UploadImage',
        # ),
    ]
