# Generated by Django 4.2.11 on 2024-05-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_light', '0022_delete_uploadimage'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='UploadImage',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #     ],
        # ),
    ]
