# Generated by Django 4.2.11 on 2024-07-23 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_light', '0024_tst_delete_uploadimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImage',
        ),
    ]
